server:
  port: 9091
  
db:  url: jdbc:oracle:thin@localhost
  user-name: root
  password: root


management:      
 endpoints:    web:      exposure:        include:
        -  "*"
     
info:
  application: "Spring Boot application for Kubernetes config map"
  version: V1          
      